### ISSUE TITLE
Retour utilisateur : Souligner les résultats 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/teletravail#11]
Retour condensé d'une utilisatrice suite à la NL du mois d'Avril :  

- Le nouveau simulateur TT est vmt super 
- Par contre dommage que les "résultats de nos économies" ne soient pas souligner & surligner pour inviter d'avantage l'utilisateur à cliquer dessus et du coup faire le pont avec MCCO2 
- Pareil pour le % 

=> du coup idée, peut-être plutôt souligner les résultats et pour le coup ne pas souligner  "sur mes déplacements" qui est un peu moins important ?

**Comment by florianpanchout** [comment]
Ah oui, étrange que l'on ai pas fait ça de base. C'est corrigé

**Comment by Clem-mrtn** [comment]
Top ! Merci
