### ISSUE TITLE
Scroll bar sur pop in

### ISSUE THREAD

**Issue by martinregner** [datagir/teletravail#12]
Sur mon PC (chrome) les pop in s'affichent avec une scroll bar sur le côté droite alors qu'il n'y a rien à scroller.
Possible de les retirer ?

![image](https://user-images.githubusercontent.com/46482115/116517195-ea25b080-a8ce-11eb-94db-bd33b9433f6d.png)

**Comment by florianpanchout** [comment]
C'est corrigé. Je répercute la correction sur tous les simulateurs.

**Comment by martinregner** [comment]
Super ! 👍
