### ISSUE TITLE
Lien vers MCC pour l'équivalent de la fabrication d'un écran

### ISSUE THREAD

**Issue by martinregner** [datagir/teletravail#14]
![image](https://user-images.githubusercontent.com/46482115/121360193-7eeee580-c934-11eb-8ee7-48c6d2e03716.png)

Juste à la suite, on pourrait mettre qqc du genre :
"A titre de comparaison, la fabrication d'[un écran d'ordinateur émet autant que 1 285 km de voiture](https://monconvertisseurco2.fr/?co2=248&equivalents=27006_27002_27976_27010_206589) (248 kgCO2e)."

C'est peut-être à valoriser autre part sur la page. Qu'en penses-tu ?

**Comment by florianpanchout** [comment]
C'est fait !
