### ISSUE TITLE
Ajouter le temps gagné

### ISSUE THREAD

**Issue by martinregner** [datagir/teletravail#16]
Attente de la part d'un (plutôt gros) réutilisateur : ajouter la notion de temps gagné

Ex. :
_Quand j'allais au travail je parcourais 30 km aller-retour chaque jour en voiture (moteur thermique) en **xx minutes au total.**
Maintenant que je travaille de chez moi, j'économise 999 kgCO2e par an sur mes déplacements. Soit 9.99% de mon empreinte carbone annuelle.
(d'autres émissions ont peut-être augmenté)
**Je gagne chaque année l'équivalent de xx heures, soit xx journées de travail.** (ou "journées de 7h" ?)_

--> proposition règle de calcul pour les jours de travail : 7h/ jours (base des 35h)

Pour ne pas complexifier, proposition de ne pas inclure de temps dans la partie "j'affine"

**Comment by florianpanchout** [comment]
Ce n'est pas très intéressant pour notre message non ? 

Et à la fois compliqué à calculer pour nous (à quelle vitesse roule t'il ? Sans compter tous les à côté du télétravail) et simple à calculer pour lui (il sait combien de temps il mettait pour aller au travail)

**Comment by martinregner** [comment]
> Et à la fois compliqué à calculer pour nous

Sorry si pas clair : l'idée serait de rajouter un champ de saisie. Rien à calculer sauf le total annuel (même règle que pour le CO2)

Je trouve que cela complète bien le message, vu que c'est L'argument principal du télétravail quand même. Ca fait moins une fixette sur le CO2 ;)

**Comment by florianpanchout** [comment]
Toujours pas convaincu. J'ai l'impression que ça dilue le message (et complexifie l'input).

**Comment by Clem-mrtn** [comment]
=> Développement d'un iframe paramétrable pour qu'ils puissent afficher le temps s'ils le souhaitent sur le simulateur TT 
Temps nécessaire : 1/2 journée 
(travail qui pourra être repris quand on refondera l'UX/UI de TT) 

=> Disponible pour la métropole de Rennes **courant de semaine prochaine**

**Comment by florianpanchout** [comment]
J'ai tenté un affichage que je trouve pas trop lourd. 

Le calcul du temps se fait automatiquement selon la vitesse et le mode de transport choisi. On peut ensuite le modifier à la main.

J'ai ajouté un paramètre speed sur chacun des modes de transport. Il est basé sur la vitesse moyenne de chaque transport (je n'ai pas noté mes sources :/ mais c'est la première réponse Google à chaque fois)

C'est activé par défaut pour l'instant
