### ISSUE TITLE
Préciser texte "j'économise x kg CO2"

### ISSUE THREAD

**Issue by martinregner** [datagir/teletravail#2]
Préciser que seul les déplacements sont concernés et introduire la notion d'effet rebond ; ex. :

> "Maintenant que je travaille de chez moi, j'économise xxx kgCO2e par an **sur mes déplacements (d'autres émissions ont peut-être augmenté par ailleurs)**.

Eventuellement, rendre possible le clic sur "d'autres émissions" soit via une pop up soit via une ancre pour être amené au texte sur ce sujet ("Ne sont pas non plus inclus...")

**Comment by florianpanchout** [comment]
J'ai réduis et rendu le texte cliquable. Le bloc de texte est trop imposant sinon :/  C'est suffisant ?

**Comment by martinregner** [comment]
Hum... pas tout à fait ;)
La modale n'est pas forcément visible pour tous.

Et avec une parenthèse en + petit (comme pour le vol d'oiseau sur MIT) : _(d'autres émissions ont peut-être augmenté)_

**Comment by florianpanchout** [comment]
Fait

**Comment by martinregner** [comment]
deal ;)
