### ISSUE TITLE
Avant je télétravaillais déjà

### ISSUE THREAD

**Issue by martinregner** [datagir/teletravail#3]
Il faut donc procéder en se disant, combien de jours j’allais au travail avant et que je télétravaille maintenant.

Ex. si 4 fois avant et que sur ces 4 fois, il n’y a que 3 jours télétravaillés actuellement, il ne faut pas renseigner 4. Il faut plutôt raisonner en différence.

Est-ce que ce serait plus clair en écrivant : "_Chaque semaine, j’allais au travail xx jours de plus qu’aujourd’hui …_ " ?

**Comment by florianpanchout** [comment]
Fait
