### ISSUE TITLE
Petit bug affichage bouton sur mobile

### ISSUE THREAD

**Issue by martinregner** [datagir/teletravail#4]
![SmartSelect_20210406-102904_Firefox](https://user-images.githubusercontent.com/46482115/113682386-614a9900-96c3-11eb-9141-635444fdf30f.jpg)

**Comment by Clem-mrtn** [comment]
J'ai le même bug d'affichage des boutons sur mon ordi 
![image](https://user-images.githubusercontent.com/76995768/113715276-9bc72c80-96e9-11eb-8cbc-4e17a360e769.png)

**Comment by florianpanchout** [comment]
Corrigé
