### ISSUE TITLE
Design : des utilisateurs ne voient pas qu'ils peuvent cliquer sur le texte en turquoise

### ISSUE THREAD

**Issue by martinregner** [datagir/teletravail#5]
Le souligner pour être plus explicite ?

**Comment by Clem-mrtn** [comment]
J'irai même plus loin, je rajouterai une mini flèche en plus de l'animation & du surlignage, comme tu avais déjà fait sur _**Mon Impact Transport**_ pour indiquer notamment qu'il faut cliquer pour dérouler la liste des moyens de transports 

+Animer le "curseur" (fin le typing qui clignote je sais pas comment ça s'appelle :p )  pour renseigner les nombres de KM ?

**Comment by florianpanchout** [comment]
C'est fait !
