### ISSUE TITLE
Slider Contact

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/teletravail#6]
Revoir le contenu de " Contact " pour clarifier les call to action & les différents moyens de contact 

=> Bloc formulaire :  Est-ce qu'on se garde la forme formulaire ? Si oui, juste pour remonter les issues & les questions ? 

=> Bloc **_"Vous souhaitez réutiliser les données brutes ?"_** : je rajouterai la phrase "_Vous souhaitez réutiliser les données brutes_ **ou intégrer ce simulateur à votre site**".  Sinon top 

=> Je ne remettrais pas le petit bloc **_"Vous souhaitez réutiliser le code du simulateur ?"_** qui est très bien déjà dans le slider **"Intégrer ce simulateur"**

**Comment by martinregner** [comment]
On enlève tout le texte au dessus du formulaire.

Sujets de contact qui envoient un mail à datagir@ademe.fr + création de prospect dans Pipedrive avec étiquette "Formulaire Nom du simulateur" : 
- J'ai besoin d'aide pour intégrer le simulateur
- Je veux en savoir plus sur Datagir

Remontée de bugs / suggestions d'amélioration du simulateur --> Airtable : 
- J'ai trouvé un bug
- Je veux proposer une amélioration

+ des spécifiques à chaque simulateur (ex. Il manque un mode de transport)

**Comment by florianpanchout** [comment]
Fait, sauf l'intégration Airtable / Pipedrive pour l'instant. (les mails s'envoient soit à datagir@ademe.fr, soit à mon adresse)

**Comment by florianpanchout** [comment]
Intégration faite :

Pour Airtable ça va dans ce tableau : https://airtable.com/tblUCIUKlR7dYWTln/viwGqUeohJ0HTwZsC?blocks=hide

Pour Pipedrive, je n'arrive pas à créer un lead sans l'associer à un contact. Du coup je crée un contact : https://datagirademe.pipedrive.com/person/715

Est ce que c'est cohérent ?

**Comment by martinregner** [comment]
@Clem-mrtn qu'en penses-tu côté intégration Pipedrive ?

Pour airtable, une base par calculateur ça risque de faire beaucoup de fichier à regarder. Peut-plutôt concentrer tous les retours simulateurs dans un seul avec un label pour le calculateur en question non ?

**Comment by Clem-mrtn** [comment]
Côté Pipedrive ça a du sens oui ! Pas de soucis pour créer un contact + un lead puisque ce seront des personnes qui souhaitent intégrer le simulateur ou en savoir plus sur la Base Carbone => donc des prospects quand même qualifiés.

Donc pas de soucis de mon côté ça étoffera le carnet d'adresse

**Comment by Clem-mrtn** [comment]
Je rajouterais quand même en dessous du formulaire une adresse mail pour l'intégration du simul ou en savoir + s/ la base de données ? 
Histoire que les gens qui ont la flemme de remplir le formulaire (ça peut être désincitatif) ait un mail de contact au cas où 

Qu'est ce que vous en pensez ?

**Comment by martinregner** [comment]
Tout à fait d'accord

**Comment by florianpanchout** [comment]
Gnagnagna trop de texte gnagnagna pas assez de texte

J'ai remis le même texte d'intro que sur le site Datagir : "Vous pouvez nous écrire à datagir@ademe.fr ou utiliser le formulaire ci‑dessous :"

Ça vous va ou vous préférez en dessous ?

**Comment by Clem-mrtn** [comment]
Don't kill the messenger mais ...😄 
Je crains que mis comme ça les gens qui veulent nous remonter des "bugs" ou nous faire des commentaires et qui ont la flemme de remplir le formulaire, nous écrivent sur datagir@ademe.fr (ce qu'on évite depuis le début).

Je remettrais bien ton petit texte en dessous du formulaire plutôt : 
**Vous souhaitez réutiliser les données brutes ou obtenir de l'aide pour intégrer ce simulateur ?
Contactez nous à datagir@ademe.fr pour bénéficier de notre expertise et accompagnement.**

Ca n'empêchera pas certes les plus flemmards, qui ont envie de nous polluer, de nous envoyer directement un mail mais bon au moins on préqualifie la demande !

Qu'en pensez vous ?

**Comment by martinregner** [comment]
> Je remettrais bien ton petit texte en dessous du formulaire plutôt :
Vous souhaitez réutiliser les données brutes ou obtenir de l'aide pour intégrer ce simulateur ?
Contactez nous à datagir@ademe.fr pour bénéficier de notre expertise et accompagnement.

C'est en effet ce que j'avais retenu aussi. on enlève tout le texte SAUF ça, en dessous 😄

**Comment by florianpanchout** [comment]
C'est fait !
