### ISSUE TITLE
Slider Partager ce simulateur 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/teletravail#7]
Je trouve le bouton très bien & clair pour ma part ! 
(tout le design des boutons sur le côté + slider je trouve ça top comme call to action immédiat !) 

Par contre moi je comprends pas trop pourquoi on remet tout ce bloc là ?  

_"Comment intégrer ces données à mon site ou application ?
Vous souhaitez afficher ce simulateur sur votre site ?
Personnalisez le et intégrez le facilement grace à notre configurateur.
Vous souhaitez réutiliser les données brutes ?
Contactez nous à datagir@ademe.fr pour bénéficier de notre expertise et accompagnement.
Vous souhaitez réutiliser le code du simulateur ?
Ce simulateur est développé de manière ouverte (open source). L’ensemble du code est disponible librement._

Je trouve que ça charge le message encore une fois alors qu'on créé des petits boutons exprès pour faciliter & accompagner l'utilisateur dans sa recherche d'action. 

Qu'est ce que vous en pensez ?

**Comment by florianpanchout** [comment]
Fait
