### ISSUE TITLE
Slider Intégrer ce simulateur

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/teletravail#8]
+1 pour le bouton, moi je trouve ça assez explicite et effectivement on le retrouve sur beaucoup de site (même Github !)

Pour le bloc **"Vous souhaitez réutiliser les données brutes ?"** je rajouterais aussi : "_Vous souhaitez réutiliser les données brutes_ ou **intégrer ce simulateur à votre site** ?"

**Comment by florianpanchout** [comment]
Fait
